#!/usr/bin/env bash
# ============================================================
# install.sh — Phoenix Package Handler
# Project:   Phoenix DevOps OS / UnitedSys
# Author:    jwl247 / Phoenix DevOps LLC
# License:   GPL-3.0
# Version:   1.1.0
# ============================================================
# USAGE:
#   curl -fsSL https://raw.githubusercontent.com/jwl247/Phoenix-Package_handler/main/install.sh | bash
# ============================================================

set -e

WORKER_URL="https://pho-installer-worker.phoenix-jwl.workers.dev"
REPO_URL="https://github.com/jwl247/Phoenix-Package_handler.git"
INSTALL_DIR="$HOME/Phoenix/package-handler"
ENV_FILE="$HOME/.phoenix_env"
PHOENIX_BIN="/usr/local/bin/intake"

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[PHX]${RESET} $1"; }
success() { echo -e "${GREEN}[OK]${RESET}  $1"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET} $1"; }
error()   { echo -e "${RED}[ERR]${RESET} $1"; exit 1; }

echo -e "${BOLD}"
echo "  ╔══════════════════════════════════════╗"
echo "  ║   Phoenix Package Handler Installer  ║"
echo "  ║   UnitedSys / Phoenix DevOps OS      ║"
echo "  ╚══════════════════════════════════════╝"
echo -e "${RESET}"

# ── 1. Health check ─────────────────────────────────────────
info "Checking worker health..."
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$WORKER_URL/health")
if [ "$HTTP_STATUS" != "200" ]; then
  error "Worker unreachable (HTTP $HTTP_STATUS). Check your connection."
fi
success "Worker is live."

# ── 2. Check dependencies ───────────────────────────────────
info "Checking dependencies..."

check_dep() {
  if ! command -v "$1" &>/dev/null; then
    warn "$1 not found — attempting install..."
    if command -v apt-get &>/dev/null; then
      sudo apt-get install -y "$2" 2>/dev/null || error "Could not install $1. Install it manually."
    elif command -v brew &>/dev/null; then
      brew install "$2" 2>/dev/null || error "Could not install $1. Install it manually."
    elif command -v dnf &>/dev/null; then
      sudo dnf install -y "$2" 2>/dev/null || error "Could not install $1. Install it manually."
    else
      error "$1 is required but not installed. Install it manually."
    fi
  fi
  success "$1 found."
}

check_dep git git
check_dep curl curl
check_dep python3 python3

# ── 3. Clone repo ────────────────────────────────────────────
info "Installing to $INSTALL_DIR ..."
if [ -d "$INSTALL_DIR/.git" ]; then
  warn "Repo already exists — pulling latest..."
  git -C "$INSTALL_DIR" pull --ff-only
else
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone "$REPO_URL" "$INSTALL_DIR"
fi
success "Repo ready."

# ── 4. Directory structure ───────────────────────────────────
info "Setting up directory structure..."
mkdir -p "$INSTALL_DIR/clonepool"
mkdir -p "$INSTALL_DIR/logs"
mkdir -p "$INSTALL_DIR/sidecars"
success "Directories created."

# ── 5. PHOENIX_AUTH token ────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  info "Loaded existing config from $ENV_FILE"
fi

if [ -z "$PHOENIX_AUTH" ]; then
  echo ""
  echo -e "${YELLOW}Enter your PHOENIX_AUTH token.${RESET}"
  echo -e "  (Find it in Cloudflare → pho-installer-worker → Settings → Variables)"
  echo ""
  read -rsp "  PHOENIX_AUTH: " PHOENIX_AUTH
  echo ""
  if [ -z "$PHOENIX_AUTH" ]; then
    error "PHOENIX_AUTH cannot be empty."
  fi
fi

# ── 6. Write env file ────────────────────────────────────────
info "Writing $ENV_FILE ..."
cat > "$ENV_FILE" <<EOF
# Phoenix Package Handler — environment
# Generated by install.sh v1.1.0 on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
export PHOENIX_AUTH="$PHOENIX_AUTH"
export PHOENIX_WORKER_URL="$WORKER_URL"
export PHOENIX_INSTALL_DIR="$INSTALL_DIR"
EOF
chmod 600 "$ENV_FILE"
success "Env file written."

# ── 7. Shell profile injection ───────────────────────────────
PROFILE_LINE="[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\""

for PROFILE in "$HOME/.bashrc" "$HOME/.zshrc"; do
  if [ -f "$PROFILE" ]; then
    if ! grep -q "phoenix_env" "$PROFILE"; then
      echo "" >> "$PROFILE"
      echo "# Phoenix Package Handler" >> "$PROFILE"
      echo "$PROFILE_LINE" >> "$PROFILE"
      success "Sourced into $PROFILE"
    else
      info "Already in $PROFILE — skipped."
    fi
  fi
done

# ── 8. Symlink intake.sh ─────────────────────────────────────
if [ -f "$INSTALL_DIR/intake.sh" ]; then
  info "Linking intake to $PHOENIX_BIN ..."
  sudo ln -sf "$INSTALL_DIR/intake.sh" "$PHOENIX_BIN" && chmod +x "$INSTALL_DIR/intake.sh"
  success "intake command available globally."
else
  warn "intake.sh not found in repo — skipping symlink."
fi

# ── 9. Register machine with D1 ─────────────────────────────
info "Registering this machine..."
HOSTNAME=$(hostname)
OS_NAME=$(uname -s)
OS_VERSION=$(uname -r)

REG_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
  -X POST "$WORKER_URL/installed/register" \
  -H "Content-Type: application/json" \
  -H "X-Phoenix-Auth: $PHOENIX_AUTH" \
  -d "{
    \"hostname\": \"$HOSTNAME\",
    \"os\": \"$OS_NAME\",
    \"version\": \"$OS_VERSION\",
    \"installed_by\": \"install.sh\",
    \"install_dir\": \"$INSTALL_DIR\"
  }")

if [ "$REG_RESPONSE" = "200" ] || [ "$REG_RESPONSE" = "201" ]; then
  success "Machine registered with Phoenix D1."
else
  warn "Registration returned HTTP $REG_RESPONSE — continuing anyway. Check token if this repeats."
fi

# ── 10. Fetch glossary ───────────────────────────────────────
info "Fetching package glossary..."
GLOSSARY=$(curl -s "$WORKER_URL/glossary" \
  -H "X-Phoenix-Auth: $PHOENIX_AUTH")

PACKAGE_COUNT=$(echo "$GLOSSARY" | python3 -c "
import sys, json
try:
  data = json.load(sys.stdin)
  pkgs = data.get('results', data.get('glossary', []))
  print(len(pkgs))
except:
  print(0)
")

success "Glossary loaded — $PACKAGE_COUNT packages available."

# ── Done ─────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}  Phoenix Package Handler installed successfully.${RESET}"
echo ""
echo -e "  ${CYAN}Reload your shell:${RESET}  source $ENV_FILE"
echo -e "  ${CYAN}Run intake:${RESET}         intake <file>"
echo -e "  ${CYAN}Worker URL:${RESET}         $WORKER_URL"
echo ""
