#Requires -Version 5.0
# ============================================================
# install.ps1 — Phoenix DevOps OS / UnitedSys
# Project:   Phoenix Package Handler
# Author:    jwl247 / Phoenix DevOps LLC
# License:   GPL-3.0
# Version:   1.0.0
# ============================================================
# PURPOSE:
#   Bootstrap installer for Phoenix Package Handler on Windows.
#   Runs on a clean system with zero manual setup.
#   Clones repo, sets env vars, registers machine with D1.
#
# USAGE:
#   iwr https://raw.githubusercontent.com/jwl247/Phoenix-Package_handler/main/install.ps1 | iex
# ============================================================

$ErrorActionPreference = 'Stop'

$WORKER_URL    = "https://packages-worker.phoenix-jwl.workers.dev"
$INSTALLER_URL = "https://pho-installer-worker.phoenix-jwl.workers.dev"
$REPO_URL      = "https://github.com/jwl247/Phoenix-Package_handler.git"
$INSTALL_DIR   = "$env:USERPROFILE\Phoenix\package-handler"
$CLONEPOOL_DIR = "$env:USERPROFILE\Phoenix\clonepool"
$ENV_FILE      = "$env:USERPROFILE\.phoenix_env.ps1"

function Write-Phoenix { param([string]$Msg, [string]$Color = 'Cyan')
    Write-Host "  [PHOENIX] $Msg" -ForegroundColor $Color }
function Write-Ok      { param([string]$Msg)
    Write-Host "  [OK] $Msg" -ForegroundColor Green }
function Write-Warn    { param([string]$Msg)
    Write-Host "  [WARN] $Msg" -ForegroundColor Yellow }
function Write-Err     { param([string]$Msg)
    Write-Host "  [ERROR] $Msg" -ForegroundColor Red; exit 1 }

# ── Header ────────────────────────────────────────────────────
Clear-Host
Write-Host '  ==========================================' -ForegroundColor DarkYellow
Write-Host '   PHOENIX PACKAGE HANDLER  —  INSTALLER   ' -ForegroundColor DarkYellow
Write-Host '   USys — United Systems | jwl247           ' -ForegroundColor DarkYellow
Write-Host '  ==========================================' -ForegroundColor DarkYellow
Write-Host ''

# ── Health check ──────────────────────────────────────────────
Write-Phoenix "Connecting to Phoenix infrastructure..."
try {
    $health = (Invoke-WebRequest "$INSTALLER_URL/health" -UseBasicParsing).Content | ConvertFrom-Json
    if (-not $health.ok) { throw "Health check failed" }
    Write-Ok "Connected — pho-installer-worker v$($health.version)"
} catch {
    Write-Err "Cannot reach Phoenix worker. Check your connection."
}

# ── Check git ─────────────────────────────────────────────────
Write-Phoenix "Checking dependencies..."
try {
    git --version | Out-Null
    Write-Ok "git found"
} catch {
    Write-Warn "git not found. Install from https://git-scm.com/download/win then re-run."
    Write-Err "git is required to continue."
}

# ── Check Python ──────────────────────────────────────────────
$PY = $null
foreach ($cmd in @("python", "python3", "py")) {
    try {
        $ver = & $cmd --version 2>&1
        if ($ver -match "Python") { $PY = $cmd; Write-Ok "Python found: $ver"; break }
    } catch {}
}
if (-not $PY) {
    Write-Warn "Python not found. Install from https://python.org/downloads"
    Write-Warn "Check 'Add Python to PATH' during install. Continuing without Python..."
}

# ── Clone repo ────────────────────────────────────────────────
Write-Phoenix "Cloning Phoenix Package Handler..."
if (Test-Path "$INSTALL_DIR\.git") {
    Write-Warn "Repo already exists — pulling latest..."
    git -C $INSTALL_DIR pull --ff-only
} else {
    New-Item -ItemType Directory -Path (Split-Path $INSTALL_DIR) -Force | Out-Null
    git clone $REPO_URL $INSTALL_DIR
}
Write-Ok "Repo ready at $INSTALL_DIR"

# ── Directory structure ───────────────────────────────────────
Write-Phoenix "Creating directory structure..."
New-Item -ItemType Directory -Path $CLONEPOOL_DIR -Force | Out-Null
New-Item -ItemType Directory -Path "$env:USERPROFILE\.catalog" -Force | Out-Null
New-Item -ItemType Directory -Path "$env:USERPROFILE\.unitedsys\logs" -Force | Out-Null
Write-Ok "Directories created"

# ── Auth token ────────────────────────────────────────────────
Write-Host ""
Write-Phoenix "Phoenix Auth Token setup"
Write-Host "  Leave blank to skip (read-only mode)" -ForegroundColor Gray
Write-Host ""
$UserAuth = Read-Host "  Enter PHOENIX_AUTH token (or press Enter to skip)"
Write-Host ""

# ── Write env file ────────────────────────────────────────────
Write-Phoenix "Writing environment config..."
$envContent = @"
# Phoenix DevOps OS — Environment
# Generated by install.ps1 $(Get-Date -Format "o")
`$env:PHOENIX_WORKER_URL    = "$WORKER_URL"
`$env:PHOENIX_INSTALLER_URL = "$INSTALLER_URL"
`$env:CLONEPOOL_DIR         = "$CLONEPOOL_DIR"
`$env:PHOENIX_AUTH          = "$UserAuth"
`$env:PATH                  = "$INSTALL_DIR\intake;" + `$env:PATH
"@
Set-Content -Path $ENV_FILE -Value $envContent -Encoding UTF8
Write-Ok "Env written to $ENV_FILE"

# ── Add to PowerShell profile ─────────────────────────────────
Write-Phoenix "Adding Phoenix to PowerShell profile..."
$profileDir = Split-Path $PROFILE
if (-not (Test-Path $profileDir)) { New-Item -ItemType Directory -Path $profileDir -Force | Out-Null }
if (-not (Test-Path $PROFILE)) { New-Item -ItemType File -Path $PROFILE -Force | Out-Null }

if (-not (Select-String -Path $PROFILE -Pattern "phoenix_env" -Quiet 2>$null)) {
    Add-Content -Path $PROFILE -Value ""
    Add-Content -Path $PROFILE -Value "# Phoenix DevOps OS"
    Add-Content -Path $PROFILE -Value "if (Test-Path `"$ENV_FILE`") { . `"$ENV_FILE`" }"
    Write-Ok "Added to $PROFILE"
} else {
    Write-Ok "Already in PowerShell profile"
}

# ── Add intake to PATH permanently ───────────────────────────
Write-Phoenix "Adding intake to system PATH..."
$intakePath = "$INSTALL_DIR\intake"
$currentPath = [System.Environment]::GetEnvironmentVariable("Path", "User")
if ($currentPath -notlike "*$intakePath*") {
    [System.Environment]::SetEnvironmentVariable("Path", "$intakePath;$currentPath", "User")
    Write-Ok "intake path added"
} else {
    Write-Ok "intake already in PATH"
}

# ── Register machine ──────────────────────────────────────────
Write-Phoenix "Registering $env:COMPUTERNAME with Phoenix..."
try {
    $body = @{
        package_name = "phoenix-package-handler"
        version      = "1.0.0"
        host         = $env:COMPUTERNAME
        state        = "active"
    } | ConvertTo-Json
    Invoke-WebRequest "$INSTALLER_URL/installed/register" -Method POST -Body $body -ContentType "application/json" -UseBasicParsing | Out-Null
    Write-Ok "$env:COMPUTERNAME registered in D1"
} catch {
    Write-Warn "Registration failed — worker may be unreachable"
}

# ── Source env now ────────────────────────────────────────────
. $ENV_FILE

# ── Done ──────────────────────────────────────────────────────
Write-Host ""
Write-Host '  ==========================================' -ForegroundColor DarkYellow
Write-Host '   PHOENIX IS ACTIVE' -ForegroundColor Green
Write-Host "   Machine: $env:COMPUTERNAME" -ForegroundColor Green
Write-Host "   Handler: $INSTALL_DIR" -ForegroundColor Green
Write-Host "   Pool:    $CLONEPOOL_DIR" -ForegroundColor Green
Write-Host '  ==========================================' -ForegroundColor DarkYellow
Write-Host ""
Write-Host "  Restart PowerShell then use intake:" -ForegroundColor Gray
Write-Host "    intake.sh ./myfile.sh" -ForegroundColor Gray
Write-Host "    intake.sh status" -ForegroundColor Gray
Write-Host ""
