#!/usr/bin/env bash
# ============================================================
# install.sh — Phoenix Package Handler
# Project:   Phoenix DevOps OS / UnitedSys — United Systems
# Author:    jwl247
# License:   GPL-3.0
# Version:   2.0.0
# ============================================================
set -euo pipefail

WORKER_URL="https://packages-worker.phoenix-jwl.workers.dev"
REPO_URL="https://github.com/jwl247/Phoenix-Package_handler.git"
ENV_FILE="${HOME}/.phoenix_env"

# ── Colors ──────────────────────────────────────────────────
G="\033[0;32m"; Y="\033[0;33m"; R="\033[0;31m"; C="\033[0;36m"; N="\033[0m"; B="\033[1m"
ok()      { echo -e "${G}[OK]${N}     $1"; }
log()     { echo -e "${Y}[PHOENIX]${N} $1"; }
err()     { echo -e "${R}[ERROR]${N}  $1"; exit 1; }
warn()    { echo -e "${Y}[WARN]${N}   $1"; }
section() { echo -e "\n${B}${C}── $1 $( printf '─%.0s' {1..40} )${N}"; }

echo ""
echo -e "${Y}================================${N}"
echo -e "${Y}  PHOENIX PACKAGE HANDLER${N}"
echo -e "${Y}  UnitedSys — United Systems${N}"
echo -e "${Y}================================${N}"
echo ""

# ── Detect platform ─────────────────────────────────────────
detect_platform() {
  if [[ -n "${WINDIR:-}" ]] || [[ -n "${windir:-}" ]]; then
    echo "windows"; return
  fi
  case "$(uname -s)" in
    Linux*)               echo "linux"   ;;
    Darwin*)              echo "macos"   ;;
    MINGW*|MSYS*|CYGWIN*) echo "gitbash" ;;
    *)                    echo "linux"   ;;
  esac
}

PLATFORM=$(detect_platform)
ok "Platform detected: ${PLATFORM}"

# ── Detect package manager ──────────────────────────────────
detect_pkgmgr() {
  if   command -v apt-get &>/dev/null; then echo "apt"
  elif command -v dnf     &>/dev/null; then echo "dnf"
  elif command -v pacman  &>/dev/null; then echo "pacman"
  elif command -v brew    &>/dev/null; then echo "brew"
  else echo "unknown"; fi
}

PKG_MGR=$(detect_pkgmgr)
ok "Package manager: ${PKG_MGR}"

# ── Set paths ───────────────────────────────────────────────
PHOENIX_HOME="${HOME}/Phoenix"
INSTALL_DIR="${PHOENIX_HOME}/Phoenix-Package_handler"
CLONEPOOL_DIR="${PHOENIX_HOME}/clonepool"
BIN_DIR="${PHOENIX_HOME}/bin"

# Shell profile
if [[ -f "${HOME}/.zshrc" ]] || [[ "${PLATFORM}" == "macos" ]]; then
  PROFILE_FILE="${HOME}/.zshrc"
else
  PROFILE_FILE="${HOME}/.bashrc"
fi

# ── Check dependencies ──────────────────────────────────────
section "Checking dependencies"

require() {
  if ! command -v "$1" &>/dev/null; then
    err "Required dependency missing: $1 — install it and retry."
  fi
  ok "$1 found"
}

require git
require curl
require python3
require pip3 || sudo apt install -y python3-pip

if ! command -v sqlite3 &>/dev/null; then
  warn "sqlite3 not found — optional, continuing"
fi

# ── Create directories ──────────────────────────────────────
section "Creating directory structure"

mkdir -p "${PHOENIX_HOME}"
mkdir -p "${CLONEPOOL_DIR}"
mkdir -p "${BIN_DIR}"
mkdir -p "${PHOENIX_HOME}/intake"
mkdir -p "${PHOENIX_HOME}/logs"
mkdir -p "${PHOENIX_HOME}/workers"
ok "Directories ready"

# ── Clone or update repo ────────────────────────────────────
section "Fetching Phoenix Package Handler"

if [[ -d "${INSTALL_DIR}/.git" ]]; then
  warn "Repo already exists — pulling latest..."
  git -C "${INSTALL_DIR}" pull --ff-only
else
  git clone "${REPO_URL}" "${INSTALL_DIR}"
fi
ok "Repo ready at ${INSTALL_DIR}"

# ── Write environment config ─────────────────────────────────
section "Writing environment config"

cat > "${ENV_FILE}" <<EOF
# Phoenix Package Handler — Environment
# Generated by install.sh v2.0.0
export PHOENIX_HOME="${PHOENIX_HOME}"
export PHOENIX_INSTALL_DIR="${INSTALL_DIR}"
export PHOENIX_CLONEPOOL="${CLONEPOOL_DIR}"
export PHOENIX_BIN="${BIN_DIR}"
export PHOENIX_WORKER_URL="${WORKER_URL}"
export PHOENIX_PLATFORM="${PLATFORM}"
export PHOENIX_LOG="${PHOENIX_HOME}/logs/phoenix.log"
export PATH="\${PATH}:${BIN_DIR}"
EOF

ok "Env written to ${ENV_FILE}"

# ── Source env in shell profile ─────────────────────────────
if [[ "${PLATFORM}" != "gitbash" ]]; then
  if ! grep -q "phoenix_env" "${PROFILE_FILE}" 2>/dev/null; then
    echo "" >> "${PROFILE_FILE}"
    echo "# Phoenix Package Handler" >> "${PROFILE_FILE}"
    echo "[ -f \"${ENV_FILE}\" ] && source \"${ENV_FILE}\"" >> "${PROFILE_FILE}"
    ok "Added to ${PROFILE_FILE}"
  else
    ok "Already in ${PROFILE_FILE}"
  fi
fi

# ── Install system-wide shim ─────────────────────────────────
section "Installing system shim"

SHIM_PATH="/usr/local/bin/phoenix-handler"

SHIM_CONTENT="#!/usr/bin/env bash
source \"${ENV_FILE}\"
exec \"${INSTALL_DIR}/intake.sh\" \"\$@\""

if [[ -w "/usr/local/bin" ]]; then
  echo "${SHIM_CONTENT}" > "${SHIM_PATH}"
  chmod +x "${SHIM_PATH}"
  ok "Shim installed at ${SHIM_PATH}"
else
  # Fall back to user bin
  echo "${SHIM_CONTENT}" > "${BIN_DIR}/phoenix-handler"
  chmod +x "${BIN_DIR}/phoenix-handler"
  warn "No write access to /usr/local/bin — shim installed to ${BIN_DIR}/phoenix-handler"
  warn "Make sure ${BIN_DIR} is in your PATH"
fi

# ── Register with worker ─────────────────────────────────────
section "Registering with Phoenix worker"

MACHINE_ID="$(hostname)-$(whoami)"
REG_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
  -X POST "${WORKER_URL}/installed/register" \
  -H "Content-Type: application/json" \
  -d "{\"machine\":\"${MACHINE_ID}\",\"platform\":\"${PLATFORM}\",\"version\":\"2.0.0\"}" \
  2>/dev/null || echo "000")

if [[ "${REG_RESPONSE}" == "200" ]] || [[ "${REG_RESPONSE}" == "201" ]]; then
  ok "Registered: ${MACHINE_ID}"
else
  warn "Registration failed (HTTP ${REG_RESPONSE}) — worker may be unreachable, continuing"
fi

# ── Summary ──────────────────────────────────────────────────
echo ""
echo -e "${G}================================${N}"
echo -e "${G}  PHOENIX IS ACTIVE${N}"
echo -e "${G}================================${N}"
echo -e "  Platform : ${PLATFORM}"
echo -e "  Home     : ${PHOENIX_HOME}"
echo -e "  Clonepool: ${CLONEPOOL_DIR}"
echo -e "  Worker   : ${WORKER_URL}"
echo -e "  Profile  : ${PROFILE_FILE}"
echo ""
echo -e "  Reload shell: ${Y}source ${PROFILE_FILE}${N}"
echo -e "  Test intake:  ${Y}phoenix-handler status${N}"
echo ""
